### ISSUE TITLE
[タスク]mdlCommonDbContextからModel(コードマスタ)依存を排除

### ISSUE THREAD

**Issue by jms-admin** [jms-web/KTS#1]
## 概要
コードマスタのModelが変更されても、FunGetCodeDataTableなどの関数を修正なしで使えるようにする
Modelプロジェクト内に実装する

## 対象プロジェクト.クラス
mdlCommonDbContext

**Comment by jms-funato** [comment]
#64 と重複(+該当Issueはより広範囲に修正対象をとらえている)
