### ISSUE TITLE
手配検索　不具合一覧

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/KTS#123]
＜検索関連＞
- [x] １．検索条件で手配区分を指定しても、うまく絞り込まれない
- [x] ２．得意先に村田と入れるとエラー
　　⇒受注先コード、受注先名、カナでも検索できるように
　　⇒コード以外の文字列を指定するとエラー発生
- [x] ３．検索条件の件名がきいていない
- [x] ４．一覧に件名、製品品番の項目を追加表示
- [x] ５．一覧の製品品名のより右側をFrozunさせる
- [x] ６．検索条件に一軒も引っかからないとエラーが発生（検索件数がNullとなっている）
　⇒エラー発生後、検索をしてもエラーになる？
- [x] ７．製品品番の検索ボタンを押下しても反応なし
- [x] ８．検索中に閉じるボタンが押せる？
- [x] ９．受注日のカラを指定すると、その当日のデータが除外される
- [x] 10．受注日、納入予定日に直接入力できない（リスト選択のみ）ので直接入力可能にすること
　⇒他のPGも確認のこと
- [x] 11．納入予定日を指定するとエラー

＜手配入力　新規入力画面＞
- [x] 101．受注納期が入力されて、フォーカスを抜けたら、初期納期に同じ日付をセットしてほしい
　　⇒すでに初期納期がセットされていたら、セットしないこと
- [x] 102.単位にはコードマスタのデフォルト値を初期セットのこと
- [x] 103.購入品追加ダイアログ
　①新規入力画面同様に手配納期が入力されたら初期納期に値をセットする
　②単位にコードマスタのデフォルト値を初期セットのこと
　③備考の入力に漢字が入力できない
　④追加してすぐに変更ボタンで変更ダイアログを表示させると諸口名、手配納期、初期納期に値が入っていない　
- [x] 104.材料追加ダイアログ
　①総数に必要数／取数の計算値が入らない
　　⇒いずれかが入力されたら、総数をセットすること
　②備考の欄に漢字が入力できない
　③追加してすぐに変更ボタンで変更ダイアログを表示させると諸口名、直送先、単価確定、手配納期、初期納期に値が入らない
- [x] 105.消耗品・冶具追加ダイアログ
　①備考の欄に漢字が入力できない
　②追加してすぐに変更ボタンで変更ダイアログを表示させると諸口名、直送先、単価確定、手配納期、初期納期に値が入らない
- [x] 106.エラーでデータベースが更新できない
- [x] 107.製品品番が検索されて、製品マスタに存在した場合、単位の登録があれば、その単位を元フォームの値にセットする
　また単価にもマスタの製品原価をセットする（０の登録の場合はセットせずにハンド入力値を優先）
　⇒各タブの追加・変更ダイアログも同様　
- [x] 108.購入品の追加ダイアログで購入品番を検索ボタンで検索選択した後に購入品名、規格寸法1、2、単価（製品原価をセット）、
　単位、リードタイムに値が入っていない
- [x] 109.各構成区分追加のダイアログにて自支給区分には初期値としてコードマスタのデフォルト値をセットのこと
- [x] 110.各構成区分の追加・変更のダイアログにて必要数が修正されたら発注数に同じ値をセット。発注数が修正されても必要数は変更しない
- [x] 111.各構成区分の追加・変更のダイアログにてリードタイムが入力、修正されたらシステム日付から稼働日でリードタイム分加算した日を
　手配納期、初期納期にセット
- [x] 112.材料の追加ダイアログにて、必要数と取数をセットしても総数の値が表示されない
　　⇒総数＝必要数／取数で計算　※０割エラーに注意すること
　　⇒取り数には初期値として1をセット
- [x] 113.新規入力にも関わらず、登録すると既に他の担当者によって変更されていますのエラーメッセージで進めない
　　（テスト登録）
- [x] 114.製品区分が製品を選択したにも関わらず、構成品の追加ができない

＜手配入力　変更画面＞
- [x] 201.一覧検索後に変更ボタンを押下して変更画面が表示されると品番マスタにあるにも関わらず、エラーのビックリマークが表示される
- [x] 202.諸口名が入力必須となっている　⇒　任意入力
- [x] 203.マスタに登録済にも関わらずマスタ更新画面（はい、いいえ、キャンセル）が表示される
　⇒得意先もキーにしていないか？⇒製品品番のみをキーとする
- [x] 204.上記のマスタ更新画面でいいえを押下しても、肝心のデータの内容が更新されていない
　⇒キャンセルと同じ動作？
- [x] 205.更新エラーとなる
- [x] 206.手配番号枝番、製造番号枝番の値が最初の値の０がセットされていない。
- [x] 207.手配番号枝番が複数ある手配を選択しても、手配番号枝番が０しか選択できない
- [x] 208.過去データを表示したときに構成品の登録があるのに出てこない（手配番号DE170-0）
- [x] 209.手配番号DE170で手配番号枝番のドロップダウンリストを変更しても製造番号が変わらない
　　⇒各タブの構成品～消耗品のタブの一覧内容が更新されない
- [x] 210.属性の値がセットされない

＜参照追加ボタン＞
- [x] 301.属性の値がセットされない
- [x] 302.指定された製品の現在庫が０以上あるが、在庫数＝０となっており引き当て数を１以上で入力できない

＜手配検索の各種ボタン押下＞
- [x] 401.製造番号表ボタン押下した際のダイアログの枝番が工程の登録があるにも関わらず全部表示されてないものがある
- [x] 402.手配番号リスト出力のダイアログでどのボタンを押下しても無反応
- [x] 403.①製造番号表の製造番号枝番が表示されていない
　　②製造票を発行する際に手配納期の入力のないものを出力するとエラー
　　⇒他の項目でもFormatしている値で項目に値が入らない恐れのあるものは回避処理すること
　　⇒テストの為にFrmG020_SEIZO_BANGOを一部修正済
- [x] 404.発注確定ボタン押下時にエラー（MITU_NOがないエラー）

＜その他＞
- [x] 901.入力コントロールで漢字の入力がある個所は、IMEコントロールでひらがな入力状態にしてほしい

---
- [x] １．取消処理は状況区分が発注確定以降ではできないように
　　⇒手配済みは手配したのみで、まだ発注処理していないので取消処理は可能
- [x] ２．構成品の追加ダイアログで構成品番の検索ボタンを押下すると製品検索ダイアログの構成区分に購入品が指定される
　　⇒製品を指定すること
- [x] ３．手配入力の新規の工程の追加ダイアログで発注先の検索ボタンを押下して選択しても、発注先に値が入らない
- [x] ４．手配入力の新規の受注情報タブで受注数＝１０、引当数＝０、手配数＝２０をセットする
　　⇒▲ビックリマークが出て「在庫引当数＋手配数が受注数に達していません」と表示される
　　⇒在庫を確保するために受注数以上に手配することもあり
　　⇒そもそも引当数＋手配数で20あるので、計算がおかしい
- [x] ５．新規登録した際に正常にデータが追加されたかわからない
　　⇒変更画面でも構成品を追加しても、再度開くと追加されていない
　　⇒エラーが発生しているのであれば、エラーを表示する様
- [x] ６．工程変更ダイアログで変更ボタンを押下しても反応なし
　　⇒キャンセルで戻って再表示しても変更されていない
- [x] ７．工程の追加ダイアログで発注先の検索ボタンが効かない
- [x] ８．工程の追加ダイアログで工程符号をリスト選択し、仕入外注区分を選択
　　⇒仕入れ外注区分が未選択状態に戻ってしまう（再度選択すると選択できる）
- [x] ９．工程タブの変更ボタンを押下して内容を修正しても修正されない
　　⇒内部的に失敗しているので変更画面が閉じない？
- [x] 10.工程タブの一覧で↑工順ボタン、↓工順ボタンを押下したときに最上段、最下段にある状態だとエラーが発生する
- [x] 11.消耗品冶具の追加画面で品番の検索ボタンを押下すると、どの発注先を選択していてもダイアログの発注先が鬼頭精器になっている
- [x] 12.参照追加で手配入力を開始し、購入品の追加ダイアログで発注先（サトケン）を選択、購入品品番で検索ボタンを押下
　購入品選択ダイアログで選択して戻ると購入品品番には値がセットされているが、購入品品名に値がセットされない
　⇒その他項目でマスタから必要な項目はセットすること
＝＝＝2018/10/24追加分＝＝＝
- [x] 13.製造番号票の工程バーコードに工程CDが入っている。工程順をセットすること
- [x] 14最初の画面の一覧の横スライドバーがなくなっていて、右側のデータが見れない
- [x] 15手配入力で品番が入力されたら、品番構成マスタ、品番工程マスタより構成品、購入品、工程、消耗品のデータを一覧に表示の事
- [x] 16手配の修正は手配状況が手配済みの場合、自由に品番も変更可能とする
　　　手配状況が発注確定～出荷までは受注情報タブの一部、属性タブのみを修正可能とする
　　　手配状況が仕入済の場合は属性のみ変更可能とする

**Comment by jms-funato** [comment]
Commit: fcad96c3
1. **____** 検索条件で手配区分を指定しても、うまく絞り込まれない
現状手配データ(D01)に手配状況区分が手配済=1のものしか登録されていない？
1. **修正** 得意先に村田と入れるとエラー
検索SQL生成にてORでつないだ得意先CDの条件式にも名称が入ってしまっていた
`... OR JYUCHU_CD=村田 ...`
1. **修正** 検索条件の件名がきいていない
検索条件式に含まれていなかった
1. **修正** 一覧に件名、製品品番の項目を追加表示
列追加
1. **修正** 一覧の製品品名のより右側をFrozunさせる
ただし、品名列で固定にすると、初期画面サイズ(1280x750)だと品名以降が見切れて表示されない
デスクトップでSXGA(1280x1024)のモニタの端末だと品名以降が実質見れないことになってしまう
1. **____** 検索条件に一軒も引っかからないとエラーが発生（検索件数がNullとなっている）
	⇒エラー発生後、検索をしてもエラーになる？
	今のところ現象再現出来ていない　結果0件だと一致するレコードはありませんになるだけ
1. **修正** 製品品番の検索ボタンを押下しても反応なし
実装出来ていなかった
1. **修正** 検索中に閉じるボタンが押せる？
1. **修正** 受注日のカラを指定すると、その当日のデータが除外される
比較演算子は`>=`でも比較データを`yyyyMMddHHmmss`まで含めて行ってしまっていた
画面上`yyyyMMdd`までしか指定しないためHHmmssは`000000`になるので、
具体的な日時が入っていると当日でも除外されてしまった
1. **修正** 受注日、納入予定日に直接入力できない（リスト選択のみ）ので直接入力可能にすること
commit: e85b16f8
Nullable=Trueだと正しい日付以外はブランクに置き換えられるが、その正しい日付かのチェックを
textchangedイベントで行ってしまっていたため最初の1文字目入力時でエラー判定になって消されてしまっていた不具合を修正
1. **修正** 納入予定日を指定するとエラー
抽出条件側の入力日付が日付型のまま比較照合されてしまった=型変換エラー
DB側の型 char(8)に変換して検索SQLに組み込み

**Comment by jms-funato** [comment]
>14最初の画面の一覧の横スライドバーがなくなっていて、右側のデータが見れない

再現手順が分かりません
ちなみに初期画面サイズ(WSXGA)だと `５．一覧の製品品名のより右側をFrozunさせる`の影響で
品名以降がほぼ見えなくなりますが、そういうことですか？

>16手配の修正は手配状況が手配済みの場合、自由に品番も変更可能とする
手配状況が発注確定～出荷までは受注情報タブの一部、属性タブのみを修正可能とする
手配状況が仕入済の場合は属性のみ変更可能とする

*手配状況区分* に *仕入済* はないのですが `SC05_GET_HACYU_DATA()` で取得できる
*発注状況区分* の `3:仕入済`のことでしょうか
もし *発注状況区分* だとした場合、SC05の引数として必要な *伝票番号* と *発注分割連番* が手配構成単位で結びつくものなので、手配データ(D01 or V06 TEHAI_NO, TEHAI_ENO)に結びつく各手配構成データ(D02 or V08) から取得した *発注状況区分* のうち、
最大のものがその手配データの *発注状況区分* になるカンジでしょうか

**Comment by jms-funato** [comment]
@jms-fukuta へ
D01_TEHAI_DATAに取引先担当名の項目がないので客先担当者名が手配毎に保存されないですが、
取引先マスタに保存した1名のみの表示でいいのでしょうか
![image](https://user-images.githubusercontent.com/20087685/47546949-7afe2880-d92e-11e8-88e0-bbe8e187ddd7.png)

**Comment by jms-fukuta** [comment]
2018/10/28　追記
　①新規登録時にD01の発注予定数に値が０で入っている
　　⇒発注予定数には発注数と同じ値を入れること
　②まだ変更時のダイアログを出した時に初期納期、納期、単価確定フラグなどの値がセットされていない
　③追加更新しても属性がセットされていない
　④製品を検索する際には、得意先と製品品番を紐づけて検索しないこと
　⑤品番マスタにある品番を入力しても、それに対応した製品品名がセットされない
　　⇒最初にセットした品番の品名のときのみ表示され、あとは表示されない
　⑥マスタにある品番で品番工程マスタにある品番を指定しても、デフォルトで工程が表示されない
　　材料も追加されない
　　構成品に親製品の品番がセットされてしまう
　⑦取引先検索で取引先CD＝6の鈴木特殊鋼㈱が出てこない
　　⇒鈴木特殊鋼㈱はマスタ登録上、取引先種別＝仕入、仕入外注区分＝仕入となっている
　　⇒得意先の指定はいらない
　⑧工程追加ダイアログで数量、単価を入力しても金額が更新されない
　⑨材料追加の画面で材料コードに「072」と入力すると材質名は表示されるが、入力した材質コードには0と表示される
　　「72」と入力するとただしく72と表示される
　⑩諸口名が入力必須となっている⇒必須でない
　⑪新規登録した後に各工程のタブ等を登録修正可能となっている
　　⇒登録ボタンを押下すると他の登録があるエラーで更新できない　
　　⇒新規登録した後に登録不可にするか画面を閉じるか？
　　⇒画面の採番された手配番号を確認したいので出したほうがいい
　　⇒登録ボタンは押せないようにする
　⑫新規追加画面で得意先をドロップダウンリストで選択する際に必ず２回選択しないと選択できない
　⑬新規追加画面で得意先に鬼頭精器、製品区分＝製品を選択。品番に06H-574F-006-001Aを入力すると実行時エラー
　　⇒VWM06_SEIHINを見ると発注先CDに０がセットされている。得意先に関係していない？
　　⇒20100340210 13357の品番は表示される
　⑭何分もかけて新規登録しようとしても、ほかの作業者がすでに更新しているエラーで登録できず
　　変更画面で変更するとエラー、テストできない
