### ISSUE TITLE
[バグ報告]M01DODE　仕入締年月変更ボタン押下時エラー

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#13]
# 概要
M01DODE　仕入締年月変更ボタン押下時エラー
# 再現手順

# 修正しないとどう困るか

# 原因

# 修正案

# 参考画像
![image](https://user-images.githubusercontent.com/36468213/36414214-dd0e20bc-1664-11e8-9897-210b75c8d9c5.png)

**Comment by jms-funato** [comment]
# 原因
更新処理時、備考欄が入力されていない場合、ブランクを付与する処理が抜けていた
