### ISSUE TITLE
2018/11/08 不具合一覧

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/KTS#142]
- [x] １．手配入力で受注納期と初期納期が連動しない
- [x] ２．消耗品冶具のリードタイムを指定しても、追加できない
- [x] ３．手配番号：TBL08001で同じように追加した構成品のデータでD01のレコードの57705-26630-00-06の引当数に-200が入っている
→構成品の引当数=ルート製品受注数 - 構成品の発注数となっていたが、そもそも構成品の引当数はルート製品の受注数とは直接は関係ないはずなので、ルート製品登録時は構成品の引当数=0とする
- [x] ４．D01の構成品の受注数に発注数と同じ値がセットされていない
- [x] ５．手配番号枝番で１以上が選択されたら、受注日、初期納期は親の値を引き継ぐので使用不可
- [x] ６．１以上の手配番号枝番で製品構成品マスタ、製品工程マスタからデータを取得する際には発注予定数には受注数×必要数をセットすること
- [x] ７．購入品の必要数と発注数の数字を変更しようとするとおかしな動作をする
- [x] ８．手配番号枝番で１以上のデータを選択して登録データを表示すると購入品、材料で登録されているはずなのに、表示されない
　　⇒手配番号枝番０で１の枝番の購入品、材料が表示されてしまう
　　⇒工程は手配番号枝番が１で正しく表示されている
- [x] ９．複数手配番号枝番があるデータで、工程タブを選択した状態で手配番号枝番を切り替えると実行時エラー
- [x] 10．構成リストで手配番号枝番が１以上の構成品の手配番号枝番が記載されていない
　　⇒手配番号の記載のあるデータは、バーコードの表示も必要
　　また一覧の引当数に必要数？が表示されている
　　⇒手配数（発注数）を表示すること
- [x] 11.製造番号票、構成リストの印刷ダイアログで枝番が１以上のものが選択できない
　　⇒手配番号：TBL08001で確認
- [x] 12.購入品（変更）タブでリードタイムを修正すると、発注数が変更される？
- [x] 13.手配済みの状態で変更されない項目
    - [x] ①属性区分タブの内容
    - [x] ②構成品タブの発注先、発注予定数、単位、単価、単価確定
**発注先は仕様書上は変更不要になっていた**
    - [x] ③購入品タブの諸口名、発注数、単位、単価、リードタイム、手配納期、初期納期、規格寸法1、規格寸法2、メーカー、追加工、備考
    - [x] ④工程タブの工程符号、発注先、諸口名、直送先、単価、必要数（必要数を修正すると０でセットされる？）、発注予定数、
　　リードタイム、手配納期、手配納期、初期納期、機械、備考
    - [x] ⑤材料タブの材寸、発注先、諸口名、直送先、必要数、発注数、取り数、単価～以降すべて
    - [x] ⑥消耗品は追加できないので、確認できず 
- [x] 14.手配番号枝番が1以上あるデータを参照追加すると、手配番号枝番がセットされている状態になっている
- [x] 15.参照追加を押下すると、手配状況に見積状況となっている（手配済を初期表示）
- [x] 16.図番ファイルの保存先の指定は？INIファイルで実施？
- [x] 17.V08＿TEHAI_KOSEI.vbのモジュールの中で発注数のセクションンにて、TORI_SU＝０の時に０割オーバーフローエラーが起きる
　⇒過去データを参照する際に、TORI_SU＝０のデータが存在するのでビューで修正する方向とする
- [x] 18.構成品、購入品、工程、消耗品を新規で追加したときにデフォルトで必要数に１が入っているので、発注数には必要数×受注数をデフォルトでセットのこと
- [x] 19.手配状況リストが印刷できない
　⇒テンプレートがない？パスが通ってない？

**Comment by jms-funato** [comment]
>11.製造番号票、構成リストの印刷ダイアログで枝番が１以上のものが選択できない
　　⇒手配番号：TBL08001で確認

V08の親手配枝番を構成品は親手配の枝番、購入品その他は自身の手配枝番を見るように変更したうえで、構成品登録があるデータで出力内容を確認(TBL09002)

> 16.図番ファイルの保存先の指定は？INIファイルで実施？

D01_CODE (KOMO_NM,VALUE)=(ファイル保存先,ROOT )にて指定
開発サーバでは```\\Jmssrv3\d\DEV\鬼頭精器\PGM\TEST\ファイル保存先\```
