### ISSUE TITLE
見積登録の不具合

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/KTS#173]
製品品番　「T32406A03-S」でテスト
- [x] １．見積新規入力で製品マスタ情報を読み込で読み込ませた際に、構成品タブ、購入品タブ、材料タブの一覧に発注先が表示されていない（消耗品タブも同様に確認のこと）
→一覧に表示する発注先略名のフィールド名がV04_MITU_KOSEIとVWM07_SEIHIN_KOSEIで異なっていたため読み込まれなかった
- [x] ２．見積新規追加で製品品番を検索して、入力必須項目を入力しても、登録ボタンが活性化されない
　⇒　タブの内容を修正等しないと活性化されない？
- [x] 3．見積を新規登録して、変更画面が表示されるが、登録した見積番号のデータが表示されず、前に登録した見積NOのデータが表示される
- [x] 4．見積を新規登録（T32406A03-SをT32406A03-S123に品番修正）して、そのまま登録すると材料の材質コードが０で登録されている⇒消耗品を登録するとおかしい？
再現条件不明
#174 2の不具合修正により表示されなくなった可能性がある
- [x] 5．見積を新規登録してマスタからデータ取得した際に属性が初期表示されない
TK01_ZOKUSEIからTORI_CDの条件を除外
- [x] 6．材料タブの一覧をダブルクリックしても変更ダイアログが表示されない
イベントハンドラの設定ミス
- [x] 7．見積出力すると２枚に分かれて出力されてしまう（プリンタふぉらいばに依存する？）
- [x] 8．売りの金額を修正後に一覧に戻り、見積出力で金額が更新前の金額で出力される
　　⇒更新した後にグリッドのデータが更新されていない為？
→保存処理後の閉じるボタンクリック時はDialogResult.OKを送るように修正
- [x] 9．取引先マスタで「ﾌｼﾞ」で検索してもフジの客先が出てこない
　　⇒開発環境では出るが、本番環境では検索されない（文字コードの問題？）
→取引先CDでの検索方法修正の対応モレが原因

**Comment by jms-fukuta** [comment]
7．見積出力すると２枚に分かれて出力されてしまう
に関して、PDFで出力しても２枚に分かれる

[b.pdf](https://github.com/jms-web/KTS/files/2766671/b.pdf)

**Comment by jms-funato** [comment]
@jms-fukuta 

#### 7.見積出力について
dev_fukuta環境のTEMPLATEファイルが更新されていないのが原因でした

現状INI・TEMPLATEファイルはgitで管理しているため( #156 )、
最新ファイルをデバッグ時やEXE実行時の参照パスである```D:\DEV_Fukuta\鬼頭精器\PGM\```でも利用できるようにシンボリックリンクを貼っておいたので、最新のTEMPLATEファイルにて出力されるはずです
