### ISSUE TITLE
[要望]M01CODE  設定値取得

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#49]
# 概要

# 目的
備考の設定値取得
# 提案内容
P18_締め処理、仕入締め確定処理ボタン押下時コードが見やすくなる。
他のBizApp.MastaApp等で使用できる。
# タスク

**Comment by jms-funato** [comment]
### 対応保留理由
- #1 のリファクタ課題であるJMS_COMMONからModel依存性を排除する方針と逆向するため
- 単なるIssueの作成テスト
