### ISSUE TITLE
[バグ]VisualStudioからリモートリポジトリの同期ができない

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#53]
## 概要
フェッチ、プルは出来るが、プッシュが出来ない。

## 参考資料(スクリーンショット等)
![image](https://user-images.githubusercontent.com/36468213/36571862-4a02ec2a-187c-11e8-9885-ba0433a40edd.png)

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
Githubにリモートログイン形式で上手くアクセス出来ないみたいなので、
この機会にGithubへの接続をSSH方式(より強固なセキュリティ)に切り替えます。
SSHに切り替えれば、ログイン用のダイアログも表示されなくなると思います。
正常に同期が取れたら、Closeして下さい。

1.SSHの公開鍵を作成しGithubに登録する手順
http://monsat.hatenablog.com/entry/generating-ssh-keys-for-github

2.ssh用のリポジトリアドレスを取得
![53_1](https://user-images.githubusercontent.com/20087685/36573495-b10e6072-1884-11e8-8a3c-4e999dfd7339.gif)

3.Visual Studioのフェッチ・プッシュ用のアクセスアドレスを変更
![53_2](https://user-images.githubusercontent.com/20087685/36573347-cf1aa400-1883-11e8-9258-26837fb362f6.gif)
