### ISSUE TITLE
[タスク]String型の有無判定条件式の置き換え

### ISSUE THREAD

**Issue by jms-funato** [jms-web/KTS#59]
## 概要
String型の有無をIf文等の判定条件に使用している箇所で、空文字("")しか考慮していない箇所があるので、以下のコード変換例のようにメソッドに置き換える
IF文で＝True　＝Falseの記述は省略する(＝Falseの場合は真偽の入れ替えを忘れずに)
## コード変換例
```vb.net
'### NG 
If mtxLEAD_TIME.Text = "" Then
   hogehoge
End If
'↓
'### OK
If mtxLEAD_TIME.Text.IsNullOrWhiteSpace Then
   hogehoge
End If
```

```vb.net
'### NG 
If mtxLEAD_TIME.Text <> "" Then
   hogehoge
End If
'↓
'### OK
If mtxLEAD_TIME.Text.IsNullOrWhiteSpace Then
Else
   hogehoge
End If
```

## 対象プロジェクト.クラス
ソリューション全体(KTS_MODELは除く)

## 対象コードの探し方
対象プロジェクトのコードファイルを開いた状態でビルドして、
エラー一覧の分類:メッセージで表示される**CA1820**が対象コード
![image](https://user-images.githubusercontent.com/20087685/36585687-373bbcde-18c2-11e8-907d-4dcadd6122cf.png)

## 通知が出ない場合
Visual Studioに「Microsoft Code Analysis 2017」プラグインをインストールしてください。

![59](https://user-images.githubusercontent.com/20087685/37808134-4eb222a6-2e8c-11e8-9ffa-8fafeea30ccb.gif)

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
とりあえず**M020_取引先マスタ**を見てみましたが、 まだ残っていますよ。
FrmM020.vb 906行目とか。
エラー一覧のメッセージ表示処理(コード分析処理)が実行出来ていないかもしれないので、
もう一度クリーン→リビルドして見てください。

**Comment by jms-arai** [comment]
材料検索ダイアログ用のソース内に、不正なソースが残っています
再度確認願います
If mtxZAISITU_NAME.Text.Trim <> "" Then
