### ISSUE TITLE
[タスク]現行実績データ移行用ストアドプロシージャ作成

### ISSUE THREAD

**Issue by jms-funato** [jms-web/KTS#67]
## 概要
現行データを新システムのマスタに取り込むためのストアドプロシージャを作成する。
おそらく、テーブル毎に変換処理が必要となるため、ストアドも個別に作成する。

## 旧DB
kitou_old.kitou2

## 現行(旧システム)テーブル仕様書
\\jmssrv2\D\DEV\鬼頭精器_新システム\Doc\旧システム資料\旧システムテーブル定義書.xlsx

## 対象テーブル(旧実装名)
- [x] D01.手配データ TRN_Thi
- [x] D02.手配構成データ TRN_ThiKsi
- [x] D03.手配工程データ TRN_ThiKti
- [x] D04.発注明細データ TRN_HycyH, TRN_HycyD
- [x] D05.受入実績データ TRN_Knsi ? 
- [x] D06.仕入データ TRN_SirH, TRN_SirD
- [x] D07.在庫データ MST_Zik
- [x] D09.作業実績データ TRN_SgyJsk
- [x] D10.完成データ WRK_KnsRslt
- [x] D11.入出庫データ TRN_NykSyk
- [x] D13.出荷データ TRN_SykkD, TRN_SykkD
- [x] D21.棚卸実績データ TRN_Tnors
- [x] D22.配膳実績データ TRN_HIZN
- [x] R01.在庫更新履歴データ TRN_ZikHsi

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
ベース部分だけ出来ている**[STW02_DATA_IKO_D02]**を参考に、
**[STW02_DATA_IKO_D03]**～**[STW02_DATA_IKO_R01]**のストアドを作成して下さい。
具体的なフィールドの紐づけはこちらでやるので、
INSERT文の形式さえ整えておいてくれればOKです。

**Comment by jms-oonishi** [comment]
保存場所：D:\DEV\鬼頭精器\Doc\DB\Stored

**Comment by jms-oonishi** [comment]
@user_name

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
メンションの書き方をしっかり伝えていなかったので、コメントで残しておきます。
特定の担当者へ通知を送るには、以下のように@を入力後、メンバー名を選択or入力します。

![67](https://user-images.githubusercontent.com/20087685/37190852-9f89fba6-239f-11e8-95d8-995fac7b232b.gif)
