### ISSUE TITLE
[バグ]M020取引先マスタ　 変更時エラー

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#69]
## 概要
データ変更時エラー
## 再現手順
変更ボタン押下時
## 修正しないとどう困るか
データ変更不可
## 原因(主に実装担当者が記入)
データを移行したことにより更新日時（EDIT_YMDHNS）の値に空欄が入っているため文字列がdatetime型として認識できずエラーが発生
## 修正案(主に実装担当者が記入)
正しい日付に変更する
## 参考資料(スクリーンショット等)
![image](https://user-images.githubusercontent.com/36468213/37196361-d936e23c-23b9-11e8-948f-a755be71f6df.png)
![image](https://user-images.githubusercontent.com/36468213/37196486-5ada072e-23ba-11e8-8bd2-14308b679934.png)

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
データ移行ストアド[STW01_MASTER_DATA_IKO]の処理上は
EDIT_YMDHNSも現在日時で更新されるはずですが、
念のため再度実行してみて下さい。

```vb.net
EXECUTE [dbo].[STW01_MASTER_DATA_IKO] 'M02'
```

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
処置完了してCloseしてもらうのはいいんですが、
後に同様の現象が発生した際に参考となるように、
最終的な対処方法もコメントに残しておいて下さい。
「再度データ移行ストアドを実行したら、反映された」など

また、↓これは起きている事象であって真の原因ではないため、
真因が分かった場合は追記するとより有用な情報となります。
> ## 原因(主に実装担当者が記入)
> データを移行したことにより更新日時（EDIT_YMDHNS）の値に空欄が入っているため文字列が?
> datetime型として認識できずエラーが発生

↓
---
~~~データを移行したことにより更新日時（EDIT_YMDHNS）の値に空欄が入っているため~~~
~~~文字列が?datetime型として認識できずエラーが発生~~~
↓
ストアドを再度実行したところ、正しく更新されたため、原因不明。
