### ISSUE TITLE
[バグ]M020　取引先マスタ　変更時エラー

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#70]
## 概要
データ変更時エラー
## 再現手順
変更ボタン押下時（売税区分・売税端数処理区分・仕税区分・仕税端数処理区分・支払日・締め日が空欄のデータ）
## 修正しないとどう困るか
変更不可
## 原因(主に実装担当者が記入)
データ移行した際に売税区分・売税端数処理区分・仕税区分・仕税端数処理区分・支払日・締め日等にNULLの値があるデータが登録され変更時にエラーが発生してしまった。
## 修正案(主に実装担当者が記入)
NULL許可されていないものに値を入れる
## 参考資料(スクリーンショット等)
![image](https://user-images.githubusercontent.com/36468213/37196704-31c4169e-23bb-11e8-989a-96f66f0c91ff.png)
![image](https://user-images.githubusercontent.com/36468213/37196983-3aa3adaa-23bc-11e8-9bfe-f657e642cf2b.png)

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
マスタデータ移行ストアドの処理にて、
旧テーブルのSELECT箇所にNullチェック+ブランク置き換え処理を追加して下さい。

## 修正対象フィールド
 - 文字列型(char,varchar,nchar,nvarchar)
 - キーではない

## 修正箇所
```sql
SELECT [新テーブル]
(,,,)
SELECT
(,,,)←**ここ**
FROM [旧テーブル]
```

## 修正例
```sql
 [DISP]--3
```
↓
```sql
  ISNULL([DISP],' ')--3
```

**Comment by jms-oonishi** [comment]
@jms-funato 
isnull([TntCd],' ') この形にしてもエラーが発生する場合はどうしたらいいですか？

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
エラーの種類が何なのかは分かりませんが、そのフィールド名からすると
旧システムは文字列型で新システムでは数値型になった項目ではないですか？
その場合ブランク文字じゃなくて0を代入しないと型変換エラーになると思います。

**Comment by jms-oonishi** [comment]
@jms-funato 
項目は売税端数処理区分、仕入端数処理区分です。
isnull([UriZeiKbn],'0')--16
0を代入した場合データに０が入りませんでした。
なので
isnull([UriZeiKbn],'1')--16
,isnull([SirZeiKbn],'1')--17
１を代入したら一部分を残して１が登録されました。
何故空欄の値ができてしまうのかわからないです。
![image](https://user-images.githubusercontent.com/36468213/37262353-f1c4f112-25e5-11e8-8683-2f0ae28f49e9.png)

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
値は0 or 1 ですが型はchar(1)のフィールドですね。
SQLServerのisnull関数はブランク文字も入っていない完全な空のみを検知するため、
空欄になるデータにはブランク(半角スペース)が入っていると思います。
なので、isnullチェックだけでなく、
「Trimでブランクを除いた上で空文字なら'0'を代入する」でいいかと思います。

```sql
,IIF(DATALENGTH(RTRIM([フィールド名])) > 0,[フィールド名],'0')
```

**Comment by jms-oonishi** [comment]
売税区分、仕税区分売税端数処理区分、仕税端数処理区分を
,IIF(DATALENGTH(RTRIM([フィールド名])) > 0,[フィールド名],'0')
に変更することでエラーが発生しなくなった。
