### ISSUE TITLE
[タスク]G160 出荷入力処理 リファクタリング

### ISSUE THREAD

**Issue by jms-funato** [jms-web/KTS#78]
わざわざissue化するまでもないですが、たまたま見つけて気になったので上げておきます。
以下のコード、動作上は問題ないですが、もう少し簡略化出来ます(コメント行除いて6行くらいに)
あと、プロジェクト名が「出力入力処理」になっているので、「出荷入力処理」に直して下さい。
 修正したら、修正後のコードをスクリーンショットか以下の方法でコメントに残して、
@jms-funatoにメンションして下さい。

## 修正対象コード
https://github.com/jms-web/KTS/blob/b952091b6b34db7ae4bb92617bf9c308bb33d144/Application/BizApp/KTS_G160(%E5%87%BA%E5%8A%9B%E5%85%A5%E5%8A%9B%E5%87%A6%E7%90%86)/View/FrmG161.vb#L219-L233

## Github上のコードをIssue等で参照する方法
1. コードファイルを開いて、開始行をクリック
1. 終了行でShift+クリック
1. **Copy permalink**…コードリンクアドレスをコピー→コメント欄に張り付ける
**Open New Issue**…コードリンクアドレス張り付け済みのIssue新規作成画面が表示される
**Copy lines**…コードを直接コピーしたい場合

![79](https://user-images.githubusercontent.com/20087685/37887195-6bea60d8-30fb-11e8-88be-e34dcbe72ba8.gif)

**Comment by jms-oonishi** [comment]
![image](https://user-images.githubusercontent.com/36468213/37896031-d9d80736-311d-11e8-8550-076d607cd797.png)
@jms-funato

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
あえて伝えませんでしたが、意図が伝わっていないみたいなのでヒントを出します。
コード中に意味を成さない構文があるため、それを除去すればもっとシンプルになるはずです。
修正前にも後にも残っています。

**Comment by jms-oonishi** [comment]
![image](https://user-images.githubusercontent.com/36468213/37940332-13c6d186-31a3-11e8-87fb-a3942c4da09b.png)
@jms-funato

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
最後のにするくらいなら↓のでいいです
![image](https://user-images.githubusercontent.com/36468213/37896031-d9d80736-311d-11e8-8550-076d607cd797.png)
