### ISSUE TITLE
[質問]P13完成入力処理　2-2-2-3　ST02在庫修正処理関数をコールする

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#79]
# 質問１
G131でストアドプロシージャ呼び出しコードを作成しています。
イデア工業さんのG100の744行目を参考にしています。イデア工業さんのコードはdgvをもとにしている為エラーが発生しませんが（イデア工業さんのコードです）
![image](https://user-images.githubusercontent.com/36468213/38284595-1337439a-37f7-11e8-993d-50ad659efeab.png)
![image](https://user-images.githubusercontent.com/36468213/38284624-2aff7e48-37f7-11e8-92d1-9b76184892e7.png)
鬼頭精器さんはdgvをもとにしていないため、呼び出し方がわかりません。考えて試しましたが
よくわからないので教えてもらいたいです。（鬼頭精器さんで作成しているコードです）
![image](https://user-images.githubusercontent.com/36468213/38284703-a6ccb0ea-37f7-11e8-8fb0-5f738fdedd60.png)
![image](https://user-images.githubusercontent.com/36468213/38284533-bd9f158e-37f6-11e8-8348-5fa6946f7691.png)

# 質問２
1-1-1（2）コムポートをオープンして、バーコードを読み取り可能状態にする
G130のForm関連でコードを作成してます
![image](https://user-images.githubusercontent.com/36468213/38284973-f81b88ee-37f8-11e8-9522-d017f66dec0e.png)
バーコード読み取り可能状態にするコードがわかりません
お忙しいと思いますがよろしくお願いします。
# 質問3
1-1-5（1）※在庫更新のST02在庫修正処置関数をコールする場合、在庫の差分を引数で渡すので修正前を記憶のこと
記憶するコードの書き方がよくわかりません。
お忙しいところ恐れ入りますがよろしくお願いします。

# タスク

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
まず質問1だけ回答します。

### 質問1-回答
ストアド呼び出し処理ですが、おしいところまで行っていますがあと一歩です。
以下の367行目でビューV08のデータを**Dataset**に取得していますが、
それを368行目のストアド実行関数(**FunExecTOUROKUProc**)に渡せていません。
- **dsList**から**Datarow**を1行ずつ取り出し、**FunExecTOUROKUProc**の
引数:ExecProcに渡す処理を作りましょう。
https://github.com/jms-web/KTS/blob/3ac712680474d467fc1dc17073cfff7192a1cb44/Application/BizApp/KTS_G130(%E5%AE%8C%E6%88%90%E5%85%A5%E5%8A%9B)/View/FrmG131.vb#L358-L376

- **FunExecTOUROKUProc**内で引数の**row**レコードから必要なフィールドを取得して、
ストアドのパラメータのSQL文字列に組み込みましょう。
(textboxから取得している箇所を**row**変数のitemプロパティに置き換え)
https://github.com/jms-web/KTS/blob/3ac712680474d467fc1dc17073cfff7192a1cb44/Application/BizApp/KTS_G130(%E5%AE%8C%E6%88%90%E5%85%A5%E5%8A%9B)/View/FrmG131.vb#L509-L534
こんなイメージ
https://github.com/jms-web/KTS/blob/3ac712680474d467fc1dc17073cfff7192a1cb44/Application/BizApp/KTS_G130(%E5%AE%8C%E6%88%90%E5%85%A5%E5%8A%9B)/View/FrmG131.vb#L574-L598

**Comment by jms-funato** [comment]
@jms-oonishi さんへ

### 質問3-回答
仕様を見たカンジだと、ST02在庫修正処理関数の引数5,6で使用するために、
完成入力画面表示時に、変更前の数量(一覧に表示されていた数量)を
FrmG131クラスのローカル変数を用意してそこに退避させておいておけばいいと思います。
仕様自体がよく分からない場合は、直接@jms-fukuta に確認して下さい。
