### ISSUE TITLE
[バグ]SQLエラー

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#82]
## 概要
データ移行した後追加、変更、削除時にエラーが発生するようになりました。
## 再現手順　
例　実行SQL
![image](https://user-images.githubusercontent.com/36468213/38407322-eeef18c8-39b3-11e8-9a78-f0aba7e798ed.png)
エラーメッセージ
![image](https://user-images.githubusercontent.com/36468213/38407354-10849030-39b4-11e8-83f0-5b2573d4f9e9.png)

## 修正しないとどう困るか
データ追加変更削除ができない
## 原因(主に実装担当者が記入)
dbo.GetSysDateString()　が認識されていない？

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
DB再構築時にスカラー値関数**GetSysDateString**を復旧し忘れてしたようです。
作成し直したので、確認して下さい。
