### ISSUE TITLE
[バグ]マスタ追加時エラー

### ISSUE THREAD

**Issue by jms-oonishi** [jms-web/KTS#83]
## 概要
レコードが1件も登録されていない状態で新規追加をすると-1から登録されてしまう
## 再現手順
M15属性マスタ
![image](https://user-images.githubusercontent.com/36468213/38479246-afd15a7e-3bf8-11e8-8a4d-26354bff78ab.png)
新規追加
![image](https://user-images.githubusercontent.com/36468213/38479266-def653c2-3bf8-11e8-889d-caf6b32d6886.png)
エラー発生個所
![image](https://user-images.githubusercontent.com/36468213/38479307-30c92526-3bf9-11e8-8f41-e232207ec48f.png)
エラーメッセージ
![image](https://user-images.githubusercontent.com/36468213/38479331-592475e8-3bf9-11e8-83d2-26b4c71f34c6.png)
追加されたｺｰﾄﾞ
![image](https://user-images.githubusercontent.com/36468213/38479346-6f2ca43c-3bf9-11e8-9375-761f72f124ec.png)

## 修正しないとどう困るか
レコードがないマスタに登録するときエラーが発生し、-1から数字が振られてしまう
## 原因(主に実装担当者が記入)
以前は　intRET = Val(dsList.Tables(0).Rows(0).Item(0)) + 1　このコードで登録可能でしたができませんでした。コードを変えて試してみましたがエラーが発生してしまいます。

**Comment by jms-funato** [comment]
@jms-oonishi さんへ
今のコードだとレコードが存在する前提の処理になってしまっているので、
ビューのレコードが存在しない場合は、1を返すように修正して下さい。
