### ISSUE TITLE
サーバーの見積・発注

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/KTS#99]
新システム向けの新サーバーの見積りを提出する

- [x] 見積作成
- [x] 発注

**Comment by jms-funato** [comment]
現状だとDBサーバ兼ファイルサーバ兼サイボウズサーバになっていますが、
ファイルサーバ機能はNASへの移行も検討

**Comment by jms-funato** [comment]
[T330 WinServer2016Essentials+Sqlserver2016 Std 32GB 2TB RAID1 構成 42万](https://www.dell.com/ja-jp/work/cart/email/index/2019097?ac=0c302106-2b9c-4bd1-8c86-77408ccae764&ref=emcartitems&stp=1&cs=jpbsd1)

[PowerEdgeT330仕様](http://japancatalog.dell.com/c/wp-content/uploads/Dell-PowerEdge-T330-Spec-Sheet-Japanese-.pdf)

**Comment by jms-funato** [comment]
[T130 WinServer2016Essentials 16GB 2TB RAID1 構成 19万](https://www.dell.com/ja-jp/work/cart/email/index/2037300?ac=6904a58d-73f5-4842-bf0d-a7cc403f31cd&ref=emcartitems&stp=1&cs=jpbsd1)

[PowerEdgeT110仕様](http://japancatalog.dell.com/c/wp-content/uploads/DELL_PowerEdgeT130_FY17Q1.pdf)
